PlayerControlsUpdate
100unity/InSaneSurvival pull request #15
Opened 2019-11-15 21:43 UTC by DavidPgl

2019-11-15 22:01 UTC, Kaes3kuch3n requested changes
Nice, danke 👍🏻 Wie haste denn das mit Passthrough rausbekommen? 😄

2019-11-15 22:01 UTC, Kaes3kuch3n commented on Assets/Scripts/PlayerController.cs
> +        cameraDistance = Mathf.Clamp(cameraDistance + cameraDistanceChange, cameraDistanceRange.min, cameraDistanceRange.max);
Ich würde erst clampen und danach die distance benutzen und nicht andersherum 😅

2019-11-15 22:01 UTC, Kaes3kuch3n commented on Assets/Scripts/PlayerController.cs
> +    private float cameraDistanceFactor;
Vielleicht mit cameraDistance kombinieren und nen Vector2 draus machen?
Also cameraDistanceFactor zu cameraDistance.x und cameraDistance zu cameraDistance.y

2019-11-15 22:01 UTC, Kaes3kuch3n commented on Assets/Scripts/PlayerController.cs
> +    private void UpdateCameraAngle(float cameraDistanceChange)
Ich würde noch 0 als default param value reinschreiben, dann sparen wir uns die bei den zwei Aufrufen

2019-11-15 22:31 UTC, DavidPgl commented on Assets/Scripts/PlayerController.cs
> +        cameraDistance = Mathf.Clamp(cameraDistance + cameraDistanceChange, cameraDistanceRange.min, cameraDistanceRange.max);
Done

2019-11-16 12:16 UTC, SamuelllG submitted a review, later dismissed
funktioniert, sieht gut aus, aber gerne nochmal Erklärung von ein paar Sachen :)

2019-11-18 14:43 UTC, Kaes3kuch3n approved these changes

2019-11-18 19:21 UTC, inkompotato approved these changes
Needs to be fixed later: 
- Camera Rotation is not frame-rate independent. Goes crazy on 165Hz, fine on 60Hz (issue created)

Nice to know:
- Camera rotation does not work when Camera Distance x is 0

2019-11-19 09:54 UTC, merged