StartMenu
100unity/InSaneSurvival pull request #25
Opened 2019-11-24 18:32 UTC by DavidPgl

2019-11-25 12:56 UTC, potatoTVnet commented on Assets/Controls/Controls.cs
> +                    ""path"": ""<Keyboard>/escape"",
wär nice wenn ESC das pause menu auch wieder schließt...

2019-11-25 13:11 UTC, inkompotato reviewed
I think the main menu issue, see comment in PlayerController, needs to be fixed before merging...
I like the menu structure, simple & clean - scaling needs some adjustment later

2019-11-25 13:11 UTC, potatoTVnet commented on Assets/Scripts/Player/PlayerController.cs
>          /// When the right mouse button is pressed, the player moves to the pressed location using a raycast and the NavMeshAgent.
Getting this error when playing the game -> returning to main menu -> play again -> continue

```
The object of type 'Camera' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object. (line 102)
```

Issues detected: returning to main menu and clicking play again opens pause menu, player position is reset

2019-11-26 00:19 UTC, DavidPgl commented
Everything should be fixed now

2019-11-26 09:36 UTC, potatoTVnet commented
Opening the options menu and pressing [ESC] to close it resumes the game but does not close the options menu.
![image](https://user-images.githubusercontent.com/31586855/69617501-9909f100-1038-11ea-9396-d9bf17841a89.png)

2019-11-26 16:09 UTC, DavidPgl commented
> Opening the options menu and pressing [ESC] to close it resumes the game but does not close the options menu.

Fixed.

2019-11-26 17:07 UTC, inkompotato submitted a review, later dismissed
looks like the bugs are fixed now...

2019-11-28 12:10 UTC, Kaes3kuch3n requested changes
Just a few small things ^^

2019-11-28 12:10 UTC, Kaes3kuch3n commented on Assets/Consts.cs
> +    public const int MAIN_MENU_SCENE = 0;
Maybe move this to a subclass already? Just for future maintainability :)

2019-11-28 12:10 UTC, Kaes3kuch3n commented on Assets/Scripts/Player/PlayerController.cs
> +        private void Pause(InputAction.CallbackContext obj) => GameManager.Instance.TogglePause();
Maybe also call this TogglePause, just to make it clearer when using it that it doesn't necessarily always pause the game

2019-11-28 12:10 UTC, Kaes3kuch3n commented on Assets/Scripts/UI/Menus/PauseMenu.cs
> +        public static PauseDelegate OnPause;
I think there's an `event` missing here ^^ Not obligatory, but better code quality, I'd say :)

2019-11-28 12:16 UTC, Kaes3kuch3n commented on Assets/Scripts/Player/PlayerController.cs
Please move getting the main camera to OnEnable, otherwise it won't update the camera reference correctly after reloading the scene :)

2019-11-28 14:25 UTC, Kaes3kuch3n submitted a review, later dismissed
:+1:

2019-11-28 22:01 UTC, inkompotato approved these changes
I trust you that this is working now

2019-11-28 22:35 UTC, Kaes3kuch3n approved these changes

2019-11-28 22:35 UTC, merged