Sanity mobs
100unity/InSaneSurvival pull request #81
Opened 2020-01-02 21:26 UTC by SamuelllG

Spawned sanity mobs are visible for all players for now.

I tried to put the sanity spawner into the player prefab, but it's not possible because the NavMeshAgent can only be rotated by setting transform.rotation directly which then causes the spawner (and all spawned mobs) to rotate with the player whenever he's trying to face a target (i.e. rotating while standing).

SanitySpawner: Spawns mobs around the player depending on the sanity level. There is a sanity mob prefab. Sanity mobs should not be killable (or we have to change some logic). Thus they despawn after a certain time depending on the player's sanity. Sanity mobs follow the player and despawn automatically when they're out of sight.

If you want to try it out, just set a lower sanity using the remote and wait a while :)

2020-01-02 21:27 UTC, SamuelllG commented
I pushed the gamescene in a commit. Not sure about what we said though... but I guess you can revert a commit with just the gamescene changes easily, sooo ...

2020-01-03 14:59 UTC, DavidPgl requested changes

2020-01-03 14:59 UTC, DavidPgl commented on Assets/Scripts/Spawner/SanitySpawnController.cs
> +        public delegate void PlayerStateChanged(int newValue);
Do you use this?

2020-01-03 14:59 UTC, DavidPgl commented on Assets/Scripts/Spawner/SanitySpawnController.cs
> +        private Dictionary<Renderer, GameObject> _spawned;
```suggestion
        private Dictionary<Renderer, GameObject> _spawned = new Dictionary<Renderer, GameObject>();
```
No need to do it in Awake. Also, if you never overwrite it with a new dictionary, you can add the keyword `readonly` as well.

2020-01-03 14:59 UTC, DavidPgl commented on Assets/Scripts/Spawner/SanitySpawnController.cs
> +            //spawned.WanderArea.center = spawnArea.center;
All this commented out code still needed?

2020-01-03 15:03 UTC, SamuelllG commented
SORRY, I forgot to do a lookover... will add descriptions, etc. !

2020-01-04 14:40 UTC, DavidPgl approved these changes

2020-01-04 20:54 UTC, thuemmels approved these changes

2020-01-05 12:12 UTC, merged