Npc lifecycle
100unity/InSaneSurvival pull request #82
Opened 2020-01-03 09:15 UTC by SamuelllG

Health, Dying and regeneration implemented

2020-01-03 14:53 UTC, DavidPgl requested changes
No summaries?:(

2020-01-03 14:53 UTC, DavidPgl commented on Assets/Scripts/Entity/Enemy/EnemyState.cs
> +                Debug.Log("x: " + x);
If not needed, remove debugs

2020-01-03 15:06 UTC, SamuelllG commented
SORRY, I forgot to do a lookover... will add descriptions, etc. !

2020-01-04 14:38 UTC, DavidPgl approved these changes

2020-01-04 21:01 UTC, thuemmels approved these changes
I think using probabilities is a bit weird when it comes to regeneration, but it works, so why not :D

2020-01-05 12:14 UTC, SamuelllG commented
I used probabilities so that the enemy doesn't regenerate consistently

2020-01-05 12:14 UTC, merged