Entity models and animations
100unity/InSaneSurvival pull request #97
Opened 2020-01-09 19:10 UTC by Kaes3kuch3n

2020-01-10 19:45 UTC, DavidPgl requested changes

2020-01-10 19:45 UTC, DavidPgl commented on Assets/Scripts/Entity/AttackLogic.cs
> +        private static readonly int AttackTrigger = Animator.StringToHash("attack");
Collect those in Consts maybe?

2020-01-11 15:18 UTC, SamuelllG approved these changes
Looks like a thing, very nice! Didn't try it out though

2020-01-11 16:44 UTC, DavidPgl approved these changes

2020-01-11 16:44 UTC, merged